V0.12
PabloLarrie/StepByStep pull request #3
Opened 2020-11-24 17:24 UTC by PabloLarrie

2020-11-24 18:01 UTC, aitorbouzas requested changes

2020-11-24 18:01 UTC, aitorbouzas commented on stepbystep/settings.py
> +    'bootstrap4',
Esto no te hace falta

2020-11-24 18:02 UTC, aitorbouzas commented
Top! Corrige solo lo que te puse que no te hace falta y apruebo el PR.

2020-11-24 18:23 UTC, PabloLarrie commented
Ready!

2020-11-25 11:15 UTC, aitorbouzas approved these changes
Perfect. Mira los cambios de líneas: has quitado 27235 y has añadido 7. Nice!

2020-11-25 11:40 UTC, merged